### ISSUE TITLE
似乎pymysql.connect 无法以dict形式传入参数

### ISSUE THREAD

**Issue by import-yuefeng** [chenjiandongx/pymysql-connection-pool#1]
## 出现异常:

我尝试使用该项目的代码, 按照README进行连接, 发现报错:
TypeError: getaddrinfo() argument 1 must be string or None

## 解决:

当我将connection_pool.py中ConnectionPool类的_create方法最后的pymysql.connect中的接受的参数从self.kwargs 改为该形式: host=self.kwargs['host'], ... passwd=self.kwargs['passwd']才能成功连接.

## 疑问

似乎pymysql.connect 无法以dict形式传入参数

## 版本信息:
Python 3.6.3
PyMySQL 0.9.2

**Comment by tmacjx** [comment]
def _create(self):
        for param in REQUIRED_PARAMS:
            if self.kwargs.get(param, None) is None:
                raise Exception(
                    "Instantiation failed, '{0}' param is not found.".format(
                        param
                    )
                )

        return pymysql.connect(self.kwargs)
代码有误
请修改为
        return pymysql.connect(**self.kwargs)

**Comment by chenjiandongx** [comment]
谢谢 已改正
